### ISSUE TITLE
Support settings.xml options

### ISSUE THREAD

**Issue by garethahealy** [takari/takari-maven-plugin#11]
It would be nice if you can read the settings.xml (if provided by -s mvn option), and use those values to set:

local repo:
- https://github.com/takari/takari-maven-plugin/blob/master/src/main/java/io/takari/maven/plugins/WrapperMojo.java#L51

remote repo URL:
- https://github.com/takari/takari-maven-plugin/blob/master/src/main/java/io/takari/maven/plugins/WrapperMojo.java#L53

Currently, if the .m2 directory isn't set to $HOME, the wrapper fails to install.

**Comment by mosabua** [comment]
This goes beyond the scope of the wrapper as it would need to understand the settings model to read and interpret it and hence a lot of parts of Maven. This goes against the idea of the wrapper. If you .m2 directory is not in $HOME .. just make symlink from there to the actual location. This is the preferred and best way to work with a different .m2 location in general anyway.

Also the remote repo URL is just a default .. you can configure it in the project specific wrapper file to be different ...

**Comment by garethahealy** [comment]
You dont need to read/interpret the settings.xml, maven already does this for you as you are a plugin (line 70/71)):
- http://maven.apache.org/plugin-tools/maven-plugin-tools-annotations/

Using the settings file is standard maven. Using custom args/hardcoded values, which are provided by the core maven environment seems to work against the idea of 'convention over configuration' which maven is built around.

If you don't want to do the code, i am happy to raise a PR. If you don't want to support this flat out, OK, i'll fork.

**Comment by mosabua** [comment]
The plugin just installs the wrapper .. we could allow that. But I am talking about the wrapper itself..  so sure.. if you are just talking about the plugin .. thats fine - go ahead and send a PR.
