### ISSUE TITLE
Best practice for file .mvn/wrapper/MavenWrapperDownloader.java

### ISSUE THREAD

**Issue by awhitford** [takari/takari-maven-plugin#26]
After running:
```
mvn -N io.takari:maven:0.7.6:wrapper -Dmaven=3.6.2
```
to upgrade from Maven 3.6.1 to 3.6.2, it adjusted `.mvn/wrapper/maven-wrapper.properties` as expected, but also unexpectedly produced the file `.mvn/wrapper/MavenWrapperDownloader.java`.

Is it best practice to add this file to Git, or is this ONLY for when you can't commit the jar?

**Comment by gzm55** [comment]
see https://github.com/takari/maven-wrapper#usage-without-binary-jar

**Comment by mosabua** [comment]
Up to you ... there is no best practice really
