### ISSUE TITLE
authentication fails for nexus oss

### ISSUE THREAD

**Issue by benbrummer** [takari/takari-maven-plugin#27]
Issue was created here https://github.com/takari/maven-wrapper/issues/142, but it looks like it belongs to this repository. Please check especially https://github.com/takari/maven-wrapper/issues/142#issuecomment-563962219

**Comment by mosabua** [comment]
This project is essentially frozen for development and new efforts are ongoing in the Apache Maven project itself. We therefore close this issue. Please find more information at https://github.com/takari/maven-wrapper#ongoing-migration-to-apache-maven and participate in the development there.
