### ISSUE TITLE
Update takari-maven-plugin to use https://repo1.maven.org for downloads

### ISSUE THREAD

**Issue by pkwarren** [takari/takari-maven-plugin#6]
https://github.com/takari/takari-maven-plugin/blob/be2cad4279721dc00750128c713df9cfe107d06b/src/main/java/io/takari/maven/plugins/WrapperMojo.java#L53
It would be good (and consistent with use of the distribution url below in the same file) to use `https` instead of `http` for these file downloads.

**Comment by pkwarren** [comment]
Thank you for the quick turnaround!

**Comment by mosabua** [comment]
You need this soon in a release?

**Comment by pkwarren** [comment]
Nope
