### ISSUE TITLE
Release 0.6.0 commits and tag missing

### ISSUE THREAD

**Issue by Stephan202** [takari/takari-maven-plugin#9]
[`io.takari:maven:0.6.0`](https://repo1.maven.org/maven2/io/takari/maven/0.6.0/) has been released, but this repository doesn't contain the relevant tag. Also, the only branch (`master`) currently points to commit c6717a39c20270b9df5c679084aad6ef5e796054, which references 0.6.0-SNAPSHOT. Perhaps the person that performed the release forgot to push the tag and associated commits?

**Comment by mosabua** [comment]
Thanks for the reminder. Done.
